variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE_API: registry.gitlab.com/michaelfmnk/peter-parker/userapi
  BUILD_TIME_TAMPLATE: +%Y.%m.%d.%H.%M.%S

cache:
  paths:
    - ./userapi/.m2/

services:
  - docker:dind

stages:
  - build-with-containers
  - deploy

build-api-with-containers:
  image: docker:latest
  stage: build-with-containers
  before_script:
    - cd ./userapi/
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - BUILD_TIME=`date $BUILD_TIME_TAMPLATE`
  script:
    - >
      docker run -t --rm
      -v /var/run/docker.sock:/var/run/docker.sock
      -v "$(pwd)":"$(pwd)"
      -w "$(pwd)"
      -u 0:0
      maven:3-jdk-8
      mvn clean package -Dmaven.test.skip=true -Pdocker -Dmaven.repo.local=.m2 -DdockerImageTags=latest -DdockerImageTags=$BUILD_TIME -DforkCount=0
    - docker push $DOCKER_IMAGE_API
  after_script:
    - cd /
  artifacts:
    paths:
      - ./userapi/target/userapi-0.0.1-SNAPSHOT.jar
    when: always
  only:
    - master


deploy:
  stage: deploy
  before_script:
    - apt-get update -y && apt-get install sshpass
  script:
    - sshpass -p "${DEPLOYMENT_SERVER_PASS}" scp -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no ./infrastructure/docker-compose.yml ${DEPLOYMENT_SERVER_USER}@${DEPLOYMENT_SERVER_IP}:~/
    - sshpass -p "${DEPLOYMENT_SERVER_PASS}" scp -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no -r ./infrastructure/balancer ${DEPLOYMENT_SERVER_USER}@${DEPLOYMENT_SERVER_IP}:~/
    - sshpass -p "${DEPLOYMENT_SERVER_PASS}" scp -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no -r ./infrastructure/recreate.sh ${DEPLOYMENT_SERVER_USER}@${DEPLOYMENT_SERVER_IP}:~/
    - sshpass -p "${DEPLOYMENT_SERVER_PASS}" scp -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no -r ./infrastructure/data ${DEPLOYMENT_SERVER_USER}@${DEPLOYMENT_SERVER_IP}:~/
    - >
      sshpass -p $DEPLOYMENT_SERVER_PASS ssh
      -o StrictHostKeyChecking=no -o PreferredAuthentications=password
      -o PubkeyAuthentication=no
      $DEPLOYMENT_SERVER_USER@$DEPLOYMENT_SERVER_IP "chmod +x ./recreate.sh; (&>log.txt ./recreate.sh &)"
  only:
    - master

