version: '3.3'
services:
  nginx:
    build: ./balancer
    restart: always
    links:
      - "user-api:user-api"
    ports:
      - "80:80"

  postgres:
    image: sameersbn/postgresql:9.6-2
    ports:
      - "5439:5432"
    command: '-N 500'
    environment:
      - DEBUG=false
      - PG_TRUST_LOCALNET=true
      - PG_PASSWORD=postgres
      - DB_NAME=peter-parker-userapi


  user-api:
    image: michaelfmnk/peterparker
    restart: always
    environment:
      - JVM_MEMORY_OPTS=-Dspring.datasource.url=jdbc:postgresql://postgres:5432/peter-parker-userapi -Dspring.datasource.username=postgres -Dspring.datasource.password=postgres -Dserver.port=8080
    links:
    - "postgres:postgres"
    ports:
     - "8080"
